/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PatentesRouteImport } from './routes/patentes'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConviteTokenRouteImport } from './routes/convite.$token'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedTarefasRouteImport } from './routes/_authenticated/tarefas'
import { Route as AuthenticatedRepertorioRouteImport } from './routes/_authenticated/repertorio'
import { Route as AuthenticatedPresencaRouteImport } from './routes/_authenticated/presenca'
import { Route as AuthenticatedPraticaRouteImport } from './routes/_authenticated/pratica'
import { Route as AuthenticatedMentoriaRouteImport } from './routes/_authenticated/mentoria'
import { Route as AuthenticatedMensagensRouteImport } from './routes/_authenticated/mensagens'
import { Route as AuthenticatedGaleriaRouteImport } from './routes/_authenticated/galeria'
import { Route as AuthenticatedDispositivosRouteImport } from './routes/_authenticated/dispositivos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConvitesRouteImport } from './routes/_authenticated/convites'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedChamadaRouteImport } from './routes/_authenticated/chamada'
import { Route as AuthenticatedCertificadoRouteImport } from './routes/_authenticated/certificado'
import { Route as AuthenticatedAulasRouteImport } from './routes/_authenticated/aulas'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PatentesRoute = PatentesRouteImport.update({
  id: '/patentes',
  path: '/patentes',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteTokenRoute = ConviteTokenRouteImport.update({
  id: '/convite/$token',
  path: '/convite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTarefasRoute = AuthenticatedTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRepertorioRoute = AuthenticatedRepertorioRouteImport.update({
  id: '/repertorio',
  path: '/repertorio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPresencaRoute = AuthenticatedPresencaRouteImport.update({
  id: '/presenca',
  path: '/presenca',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPraticaRoute = AuthenticatedPraticaRouteImport.update({
  id: '/pratica',
  path: '/pratica',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMentoriaRoute = AuthenticatedMentoriaRouteImport.update({
  id: '/mentoria',
  path: '/mentoria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMensagensRoute = AuthenticatedMensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGaleriaRoute = AuthenticatedGaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDispositivosRoute =
  AuthenticatedDispositivosRouteImport.update({
    id: '/dispositivos',
    path: '/dispositivos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConvitesRoute = AuthenticatedConvitesRouteImport.update({
  id: '/convites',
  path: '/convites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChamadaRoute = AuthenticatedChamadaRouteImport.update({
  id: '/chamada',
  path: '/chamada',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCertificadoRoute =
  AuthenticatedCertificadoRouteImport.update({
    id: '/certificado',
    path: '/certificado',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAulasRoute = AuthenticatedAulasRouteImport.update({
  id: '/aulas',
  path: '/aulas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/patentes': typeof PatentesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/aulas': typeof AuthenticatedAulasRoute
  '/certificado': typeof AuthenticatedCertificadoRoute
  '/chamada': typeof AuthenticatedChamadaRoute
  '/chat': typeof AuthenticatedChatRoute
  '/convites': typeof AuthenticatedConvitesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dispositivos': typeof AuthenticatedDispositivosRoute
  '/galeria': typeof AuthenticatedGaleriaRoute
  '/mensagens': typeof AuthenticatedMensagensRoute
  '/mentoria': typeof AuthenticatedMentoriaRoute
  '/pratica': typeof AuthenticatedPraticaRoute
  '/presenca': typeof AuthenticatedPresencaRoute
  '/repertorio': typeof AuthenticatedRepertorioRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/api/chat': typeof ApiChatRoute
  '/convite/$token': typeof ConviteTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/patentes': typeof PatentesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/aulas': typeof AuthenticatedAulasRoute
  '/certificado': typeof AuthenticatedCertificadoRoute
  '/chamada': typeof AuthenticatedChamadaRoute
  '/chat': typeof AuthenticatedChatRoute
  '/convites': typeof AuthenticatedConvitesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dispositivos': typeof AuthenticatedDispositivosRoute
  '/galeria': typeof AuthenticatedGaleriaRoute
  '/mensagens': typeof AuthenticatedMensagensRoute
  '/mentoria': typeof AuthenticatedMentoriaRoute
  '/pratica': typeof AuthenticatedPraticaRoute
  '/presenca': typeof AuthenticatedPresencaRoute
  '/repertorio': typeof AuthenticatedRepertorioRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/api/chat': typeof ApiChatRoute
  '/convite/$token': typeof ConviteTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/patentes': typeof PatentesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/aulas': typeof AuthenticatedAulasRoute
  '/_authenticated/certificado': typeof AuthenticatedCertificadoRoute
  '/_authenticated/chamada': typeof AuthenticatedChamadaRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/convites': typeof AuthenticatedConvitesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dispositivos': typeof AuthenticatedDispositivosRoute
  '/_authenticated/galeria': typeof AuthenticatedGaleriaRoute
  '/_authenticated/mensagens': typeof AuthenticatedMensagensRoute
  '/_authenticated/mentoria': typeof AuthenticatedMentoriaRoute
  '/_authenticated/pratica': typeof AuthenticatedPraticaRoute
  '/_authenticated/presenca': typeof AuthenticatedPresencaRoute
  '/_authenticated/repertorio': typeof AuthenticatedRepertorioRoute
  '/_authenticated/tarefas': typeof AuthenticatedTarefasRoute
  '/api/chat': typeof ApiChatRoute
  '/convite/$token': typeof ConviteTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/patentes'
    | '/reset-password'
    | '/admin'
    | '/aulas'
    | '/certificado'
    | '/chamada'
    | '/chat'
    | '/convites'
    | '/dashboard'
    | '/dispositivos'
    | '/galeria'
    | '/mensagens'
    | '/mentoria'
    | '/pratica'
    | '/presenca'
    | '/repertorio'
    | '/tarefas'
    | '/api/chat'
    | '/convite/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/patentes'
    | '/reset-password'
    | '/admin'
    | '/aulas'
    | '/certificado'
    | '/chamada'
    | '/chat'
    | '/convites'
    | '/dashboard'
    | '/dispositivos'
    | '/galeria'
    | '/mensagens'
    | '/mentoria'
    | '/pratica'
    | '/presenca'
    | '/repertorio'
    | '/tarefas'
    | '/api/chat'
    | '/convite/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/patentes'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/aulas'
    | '/_authenticated/certificado'
    | '/_authenticated/chamada'
    | '/_authenticated/chat'
    | '/_authenticated/convites'
    | '/_authenticated/dashboard'
    | '/_authenticated/dispositivos'
    | '/_authenticated/galeria'
    | '/_authenticated/mensagens'
    | '/_authenticated/mentoria'
    | '/_authenticated/pratica'
    | '/_authenticated/presenca'
    | '/_authenticated/repertorio'
    | '/_authenticated/tarefas'
    | '/api/chat'
    | '/convite/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  PatentesRoute: typeof PatentesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiChatRoute: typeof ApiChatRoute
  ConviteTokenRoute: typeof ConviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patentes': {
      id: '/patentes'
      path: '/patentes'
      fullPath: '/patentes'
      preLoaderRoute: typeof PatentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite/$token': {
      id: '/convite/$token'
      path: '/convite/$token'
      fullPath: '/convite/$token'
      preLoaderRoute: typeof ConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tarefas': {
      id: '/_authenticated/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof AuthenticatedTarefasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/repertorio': {
      id: '/_authenticated/repertorio'
      path: '/repertorio'
      fullPath: '/repertorio'
      preLoaderRoute: typeof AuthenticatedRepertorioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/presenca': {
      id: '/_authenticated/presenca'
      path: '/presenca'
      fullPath: '/presenca'
      preLoaderRoute: typeof AuthenticatedPresencaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pratica': {
      id: '/_authenticated/pratica'
      path: '/pratica'
      fullPath: '/pratica'
      preLoaderRoute: typeof AuthenticatedPraticaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mentoria': {
      id: '/_authenticated/mentoria'
      path: '/mentoria'
      fullPath: '/mentoria'
      preLoaderRoute: typeof AuthenticatedMentoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mensagens': {
      id: '/_authenticated/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof AuthenticatedMensagensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/galeria': {
      id: '/_authenticated/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof AuthenticatedGaleriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dispositivos': {
      id: '/_authenticated/dispositivos'
      path: '/dispositivos'
      fullPath: '/dispositivos'
      preLoaderRoute: typeof AuthenticatedDispositivosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/convites': {
      id: '/_authenticated/convites'
      path: '/convites'
      fullPath: '/convites'
      preLoaderRoute: typeof AuthenticatedConvitesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chamada': {
      id: '/_authenticated/chamada'
      path: '/chamada'
      fullPath: '/chamada'
      preLoaderRoute: typeof AuthenticatedChamadaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certificado': {
      id: '/_authenticated/certificado'
      path: '/certificado'
      fullPath: '/certificado'
      preLoaderRoute: typeof AuthenticatedCertificadoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aulas': {
      id: '/_authenticated/aulas'
      path: '/aulas'
      fullPath: '/aulas'
      preLoaderRoute: typeof AuthenticatedAulasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAulasRoute: typeof AuthenticatedAulasRoute
  AuthenticatedCertificadoRoute: typeof AuthenticatedCertificadoRoute
  AuthenticatedChamadaRoute: typeof AuthenticatedChamadaRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedConvitesRoute: typeof AuthenticatedConvitesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDispositivosRoute: typeof AuthenticatedDispositivosRoute
  AuthenticatedGaleriaRoute: typeof AuthenticatedGaleriaRoute
  AuthenticatedMensagensRoute: typeof AuthenticatedMensagensRoute
  AuthenticatedMentoriaRoute: typeof AuthenticatedMentoriaRoute
  AuthenticatedPraticaRoute: typeof AuthenticatedPraticaRoute
  AuthenticatedPresencaRoute: typeof AuthenticatedPresencaRoute
  AuthenticatedRepertorioRoute: typeof AuthenticatedRepertorioRoute
  AuthenticatedTarefasRoute: typeof AuthenticatedTarefasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAulasRoute: AuthenticatedAulasRoute,
  AuthenticatedCertificadoRoute: AuthenticatedCertificadoRoute,
  AuthenticatedChamadaRoute: AuthenticatedChamadaRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedConvitesRoute: AuthenticatedConvitesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDispositivosRoute: AuthenticatedDispositivosRoute,
  AuthenticatedGaleriaRoute: AuthenticatedGaleriaRoute,
  AuthenticatedMensagensRoute: AuthenticatedMensagensRoute,
  AuthenticatedMentoriaRoute: AuthenticatedMentoriaRoute,
  AuthenticatedPraticaRoute: AuthenticatedPraticaRoute,
  AuthenticatedPresencaRoute: AuthenticatedPresencaRoute,
  AuthenticatedRepertorioRoute: AuthenticatedRepertorioRoute,
  AuthenticatedTarefasRoute: AuthenticatedTarefasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  PatentesRoute: PatentesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiChatRoute: ApiChatRoute,
  ConviteTokenRoute: ConviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
